SYMBOLS = ["RELIANCE.NS", "HDFCBANK.NS", "SBIN.NS", "INFY.NS", "TCS.NS"]

INTERVAL = "15m"
PERIOD = "5d"

EMA_FAST = 20
EMA_SLOW = 50
RSI_PERIOD = 14
RSI_BUY = 55
RSI_SELL = 45
VOLUME_PERIOD = 20
ATR_PERIOD = 14

ATR_STOP_MULTIPLIER = 1.5
RISK_REWARD = 2.0
